// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package repositories

import (
	"go-admin/internal/models"
)

// Injectors from wire.go:

func NewUserRepository() User {
	db := models.GetDB()
	user := NewUser(db)
	return user
}
