// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package services

import (
	"go-admin/internal/models"
	"go-admin/internal/models/repositories"
)

// Injectors from wire.go:

func NewAuthService() *Auth {
	db := models.GetDB()
	user := repositories.NewUser(db)
	auth := NewAuth(user)
	return auth
}
