// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package services

import (
	"monitor/internal/models"
)

// Injectors from wire.go:

func NewUserService() *user {
	db := models.GetDB()
	servicesUser := newUser(db)
	return servicesUser
}
