app:
  name: go-admin
  debug: true
  env: local    # local, release, tests
  log_path: ./cmd
  port: 8000
db:
  engine: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: monitor
  prefix: m_
  charset: utf8mb4
  loc: Asia/Shanghai
  maxidleconns: 20
  maxopenconns: 50