app:
  name: monitor
  debug: true
  env: release
  log_path: .
db:
  enable: true
  engine: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: monitor
  prefix:
  charset: utf8mb4
  maxidleconns: 20
  maxopenconns: 50